name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: ./gradlew make

      - name: Push builds
        run: |
          cp build/*.cs3 builds/
          cd builds
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Build plugins" || true
          git push
